apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: {{ .Values.iot_consumer.bootstrap_tag }}
    from:
      kind: DockerImage
      name: {{ .Values.iot_consumer.bootstrap_image }}
    importPolicy: {}
    referencePolicy:
      type: Local
{{- if .Values.iot_consumer.updated_images }}
  - name: {{ .Values.iot_consumer.tag }}
    from:
      kind: DockerImage
      name: "{{ .Values.iot_consumer.image_location }}:{{ .Values.iot_consumer.tag }}"
    importPolicy: {}
    referencePolicy:
      type: Local
{{- end }}
