---
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: purpose-banner
spec:
{{- if .Values.clusterEnvironment }}
  text: "OpenShift Cluster Environment [{{ .Values.clusterEnvironment }}]"
{{- else }}
  text: "OpenShift Cluster Environment"
{{- end }}
  location: "BannerTopBottom" #BannerTopBottom
  color: '#fff'
  backgroundColor: '#000000'
