apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2
    from:
      kind: DockerImage
      name: quay.io/hybridcloudpatterns/iot-consumer:0.3.2
    importPolicy: {}
    referencePolicy:
      type: Local
{{- if .Values.iot_consumer.updated_images }}
  - name: {{ .Values.iot_consumer.tag | quote }}
    from:
      kind: DockerImage
      name: "{{ .Values.iot_consumer.image_location }}:{{ .Values.iot_consumer.tag }}"
    importPolicy: {}
    referencePolicy:
      type: Local
{{- end }}
