apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
  namespace: manuela-stormshift-machine-sensor
spec:
  lookupPolicy:
    local: true
  tags:
  - name: {{ .Values.machine_sensor.bootstrap_tag }}
    from:
      kind: DockerImage
      name: {{ .Values.machine_sensor.bootstrap_image }}
    importPolicy: {}
    referencePolicy:
      type: Local
{{- if .Values.machine_sensor.updated_images }}
  - name: {{ .Values.machine_sensor.tag | quote }}
    from:
      kind: DockerImage
      name: "{{ .Values.machine_sensor.image_location }}:{{ .Values.machine_sensor.tag }}"
    importPolicy: {}
    referencePolicy:
      type: Local
{{- end }}
