apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    application: anomaly-detection
  name: anomaly-detection
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: false
  tags:
  - name: {{ .Values.iot_anomaly_detection.bootstrap_tag }}
    from:
      kind: DockerImage
      name: quay.io/hybridcloudpatterns/iot-anomaly-detection:0.3.2
    importPolicy: {}
    referencePolicy:
      type: Local
{{- if .Values.iot_anomaly_detection.updated_images }}
  - name: {{ .Values.iot_anomaly_detection.tag | quote }}
    from:
      kind: DockerImage
      name: "{{ .Values.iot_anomaly_detection.image_location }}:{{ .Values.iot_anomaly_detection.tag }}"
    importPolicy: {}
    referencePolicy:
      type: Local
{{- end }}
